# Generated by Django 5.2.3 on 2025-06-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='phone number')),
                ('code', models.SmallIntegerField(verbose_name='code')),
                ('expires', models.DateTimeField(auto_now_add=True, verbose_name='expires')),
            ],
        ),
    ]
