# Generated by Django 5.2.3 on 2025-06-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_orderitem_color_alter_orderitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('discount', models.IntegerField(default=0)),
                ('expire', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
