# Generated by Django 5.2.3 on 2025-06-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
